# This workflow builds a container consisting of a few common scripts
# the scripts are used for intermediate jobs in a GeoEDF workflow

name: buildcontainer

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps in the workflow
    
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            pkg-config

      - name: Install Singularity
        env:
          SINGULARITY_VERSION: 3.7.3
        run: |
          sudo mkdir -p /usr/local/var/singularity/mnt && \
          mkdir -p /tmp/src/github.com/sylabs && \
          cd /tmp/src/github.com/sylabs && \
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz | \
          tar xzv && \
          cd singularity && \
          ./mconfig -p /usr/local && \
          make -C builddir && \
          sudo make -C builddir install && \
          mkdir ~/.singularity

      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v2

      - name: Build Container
        env:
          SINGULARITY_RECIPE: Singularity
          OUTPUT_CONTAINER: container.sif
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo $TOKEN | singularity remote add geoedf https://www.registry.geoedf.org
          singularity remote use geoedf
          singularity remote list
          dir=$(pwd)
          if [ -f "${SINGULARITY_RECIPE}" ]; then
            sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}

            if [ -f "${OUTPUT_CONTAINER}" ]; then
            singularity push -U ${OUTPUT_CONTAINER} library://geoedfproject/framework/workflowutils:latest
            else
              echo "Container build failed."
            fi
          else
            echo "Singularity recipe ${SINGULARITY_RECIPE} was not created."
          fi
